### ISSUE TITLE
ClassCastException on player join

### ISSUE THREAD

**Issue by SlimeDog** [Niall7459/HolographicExtension#12]
Spigot 1.15.1 (Jenkins 2525)
ProtocolLib 4.5.0-b439
HolographicDisplays 2.4.1-b98
HolographicExtension  1.10.7

No errors on start-up. When player joins, there are many of these per second:
```
[07:14:11] [Server thread/ERROR]: [HolographicExtension] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicExtension
java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.replacePlaceholders(PacketPlaceholderListener.java:74) ~[HolographicExtension-1.10.7.jar:?]
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.onPacketSending(PacketPlaceholderListener.java:44) ~[HolographicExtension-1.10.7.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib-4.5.0-b439.jar:4.5.0-SNAPSHOT-b439]
        at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:185) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:155) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:152) [Denizen-1.1.2-b4474.jar:?]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1410) [?:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1383) [?:git-Spigot-2ee05fe-90ef74e]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.AbstractListenerPlayInImpl.sendPacket(AbstractListenerPlayInImpl.java:50) [Denizen-1.1.2-b4474.jar:?]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenPacketListenerImpl.sendPacket(DenizenPacketListenerImpl.java:47) [Denizen-1.1.2-b4474.jar:?]
        at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:210) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:53) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:220) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:129) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1099) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
followed by
```
[07:14:11] [Server thread/ERROR]: [HolographicExtension] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for HolographicExtension
java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.replacePlaceholders(PacketPlaceholderListener.java:74) ~[?:?]
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.onPacketSending(PacketPlaceholderListener.java:44) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:185) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:155) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:152) ~[?:?]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1410) ~[?:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1383) ~[?:git-Spigot-2ee05fe-90ef74e]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.AbstractListenerPlayInImpl.sendPacket(AbstractListenerPlayInImpl.java:50) ~[?:?]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenPacketListenerImpl.sendPacket(DenizenPacketListenerImpl.java:47) ~[?:?]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:244) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:226) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1258) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1122) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$43(PlayerChunkMap.java:654) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$42(PlayerChunkMap.java:653) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$40(PlayerChunkMap.java:649) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:567) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:104) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IChunkProvider.getChunkAt(SourceFile:16) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.isChunkLoaded(CraftWorld.java:342) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:144) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:353) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1076) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
and
```
[07:14:11] [Server thread/ERROR]: [HolographicExtension] Unhandled exception number 64 occured in onPacketSending(PacketEvent) for HolographicExtension
java.lang.ClassCastException: class java.util.Optional cannot be cast to class java.lang.String (java.util.Optional and java.lang.String are in module java.base of loader 'bootstrap')
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.replacePlaceholders(PacketPlaceholderListener.java:74) ~[?:?]
        at net.kitesoftware.holograms.listener.PacketPlaceholderListener.onPacketSending(PacketPlaceholderListener.java:44) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_15_R1.NetworkManager.b(NetworkManager.java:185) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.NetworkManager.sendPacket(NetworkManager.java:155) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenNetworkManagerImpl.sendPacket(DenizenNetworkManagerImpl.java:152) ~[?:?]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1410) ~[?:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerConnection.sendPacket(PlayerConnection.java:1383) ~[?:git-Spigot-2ee05fe-90ef74e]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.AbstractListenerPlayInImpl.sendPacket(AbstractListenerPlayInImpl.java:50) ~[?:?]
        at com.denizenscript.denizen.nms.v1_15.impl.network.handlers.DenizenPacketListenerImpl.sendPacket(DenizenPacketListenerImpl.java:47) ~[?:?]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:244) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:226) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1258) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.a(PlayerChunkMap.java:1122) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$43(PlayerChunkMap.java:654) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$42(PlayerChunkMap.java:653) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.PlayerChunkMap.lambda$40(PlayerChunkMap.java:649) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_15_R1.ChunkTaskQueueSorter.b(SourceFile:58) ~[spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:567) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:104) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.IChunkProvider.getChunkAt(SourceFile:16) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.isChunkLoaded(CraftWorld.java:342) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at org.spigotmc.ActivationRange.activateEntities(ActivationRange.java:144) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:353) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1076) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.1.jar-2019-12-18-2121:git-Spigot-2ee05fe-90ef74e]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Niall7459** [comment]
Looks like citizens interfering, I'll take a look at this

**Comment by andris155** [comment]
https://github.com/Niall7459/HolographicExtension/pull/13
