### ISSUE TITLE
Feature request: configuration to disable update checking

### ISSUE THREAD

**Issue by SlimeDog** [Niall7459/HolographicExtension#4]
HolographicExtension 1.10.4

Please add configuration option to disable update checks. I have my own homegrown automagical update checker, and I disable unnecessary (by my own standards) outgoing calls at the network level, using NetworkInterceptor. So console/log is spammed with
```
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: java.io.IOException: Connect failed
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at me.lucko.networkinterceptor.interceptors.ProxySelectorInterceptor$LoggingSelector.select(ProxySelectorInterceptor.java:59)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1175)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1065)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1063)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:793)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1062)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1501)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1499)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:793)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at net.kitesoftware.holograms.updater.UpdateChecker.lambda$checkUpdates$0(UpdateChecker.java:38)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[08:01:27] [ForkJoinPool.commonPool-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Niall7459** [comment]
Sorry for this inconvenience. I'll get a config option added in the next release.

Thanks,

**Comment by Niall7459** [comment]
Added,
https://github.com/Niall7459/HolographicExtension/commit/d4c32f3eadf2dfb8bf79a391ba450f187ee136e7
Enjoy

**Comment by SlimeDog** [comment]
Much appreciated.
